### ISSUE TITLE
Emacs

### ISSUE THREAD

**Issue by bsamadi** [modelica-tools/modelica-mode#1]
After installing modelica-mode, I get this error: emacs Cannot open load file, br-start
Also, here http://www.emacswiki.org/emacs/ObjectOrientedBrowser, it says that oo-browser seems defunct as of Nov 2013. I downloaded it and ran it. I didn't get any error. Any hint on if modelica-model is still functional? If not, has it been replaced?
Thanks.

**Comment by dietmarw** [comment]
I personally only use the `modelica-mode.el` which still works fine and without any problems. I can't really say anything about the mdc-browse related parts and neither can I suggest a solution. If you come up with one feel free to send a pull request or maintain it in a fork of yours. Sorry.

**Comment by dietmarw** [comment]
There might be a chance that the original author, @rfranke, has some idea.

**Comment by rfranke** [comment]
The oo-browser support should be considered out-dated and not working anymore. It might be interesting to convert this part of the Modelica mode to Emacs Code Browser (ecb) if such functionality is needed. Having no plans into this direction at the moment though.

**Comment by dietmarw** [comment]
This has now been fixed as part of #6.
